### ISSUE TITLE
Incorrect terminology in README title

### ISSUE THREAD

**Issue by phelps-sg** [anabugaenko/powerlaw-function#23]
The README states ".. for Analysing Heavy-Tailed Functions".  However, I don't think there is a such thing as a heavy-tailed *function*.  Yes there are heavy-tailed probability distributions, and some of these distributions have density functions that follow a power-law, but the intended use-case for the repo goes beyond analysing distributions.

I think the title should be something like "A Python Package for fitting functions against a power-law".

**Comment by anabugaenko** [comment]
"Testing whether data are drawn iid from a power-law distribution. To do this, we can use, e.g. KDE, to infer the CDF from a finite sample of data, and then we can fit a power-law to the inferred CDF, similarly to [Clauset et al. 2007](https://arxiv.org/abs/0706.1062) and [Virkar and Clauset. 2012](https://arxiv.org/abs/1208.3524)."

This use case is covered by https://github.com/jeffalstott/powerlaw, although we can also support it (we would need to provide support for KDE.

The second use case:

"Testing whether a stochastic process has long memory. To do this we can infer an autocorrelation function from a finite time-series sample, and then we can fit a power-law to the inferred ACF."

Is more broadly not supported by the former, and why this library exists.

**Comment by anabugaenko** [comment]
<img width="1087" alt="Screenshot 2023-09-19 at 11 07 55" src="https://github.com/anabugaenko/powerlaw-function/assets/60014
<img width="781" alt="Screenshot 2023-09-19 at 11 10 45" src="https://github.com/anabugaenko/powerlaw-function/assets/6001401/126d286b-395e-4233-b41f-fe624aeb348e">
01/275bd3da-b0c3-41e6-9a0b-33f8e5fb08f0">

**Comment by anabugaenko** [comment]
<img width="1087" alt="Screenshot 2023-09-19 at 11 07 55" src="https://github.com/anabugaenko/powerlaw-function/assets/6001401/1f3b22ec-0776-416f-97dd-927a18a81d35">

**Comment by anabugaenko** [comment]
<img width="781" alt="Screenshot 2023-09-19 at 11 10 45" src="https://github.com/anabugaenko/powerlaw-function/assets/6001401/3724dd58-28be-4acc-bb73-5ce03ee80e39">

**Comment by anabugaenko** [comment]
clarify use-cases in README #17. Done.
